version: "3.7"

volumes:
  postgres_data:

services:
  migrate: &app
    build:
      context: .
    volumes:
      - .:/usr/src
    command: dotnet ef database update
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:3x4mpl3P455@postgres:5432/demo_development
      PORT: ${EJEMPLO_WEB_PORT:-5000}

  web:
    <<: *app
    command: dotnet watch run
    depends_on:
      - postgres
      - migrate
    ports:
      - ${EJEMPLO_WEB_PORT:-5000}:${EJEMPLO_WEB_PORT:-5000}

  postgres:
    image: postgres:11-alpine
    ports:
      - ${EJEMPLO_PGPORT:-5432}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 3x4mpl3P455